### ISSUE TITLE
reCaptcha support

### ISSUE THREAD

**Issue by gfsd3v** [pedroapfilho/2captcha-node#4]
Do you plan to add support to reCaptcha ? I would be glad to help if needed.

Thanks for the libary.

**Comment by Brostafa** [comment]
@pedroapfilho I will take stab at this :v:

**Comment by Brostafa** [comment]
@pedroapfilho Done https://github.com/pedroapfilho/2captcha-node/pull/6

Here's what I've done:

- Added reCaptcha support in src/index.js
- Created a sample CONTRIBUTING.md to explain how new devs can edit this project
- Updated README.md with an example on how to use reCaptcha
- Updated package.json to include `dev` script and added `@babel/node` and `nodemon` to devDependencies

**Comment by alechirsch** [comment]
@pedroapfilho What happened to this? The pull request was closed and never merged. Do you plan on supporting this? I may roll my own if not

**Comment by pedroapfilho** [comment]
Hello @alechirsch , I don't quite remember what happened, but this feature would be awesome!

If you can, please roll our your PR!

**Comment by alechirsch** [comment]
@pedroapfilho It looks like the PR that you closed is still valid, can you take a second look?
