### ISSUE TITLE
Add retry limit

### ISSUE THREAD

**Issue by gajus** [pedroapfilho/2captcha-node#7]
Currently `solve` will attempt to request for a solution for as long as the response is `{"status":0,"request":"CAPCHA_NOT_READY"}`. I have observed cases where this has persisted for a very long time. It would be handy to have a way to configure a hard limit or to have `cancel` method.

**Comment by pedroapfilho** [comment]
Good one! I'll work on it! It should be pretty simple. 

How many attempts do you think the default should be? Unlimited?

**Comment by gajus** [comment]
I would have a default limit relatively low, e.g. 20. I would rather be warned of the issue and become aware of it, than to have something hanging for a long time. These things are hard to notice when in production/ cluster, and could add up to a lot of wasted/ idle resources.

**Comment by pedroapfilho** [comment]
If I put 20 times it's gonna take approx 101 seconds (probably if it takes more than that, something went wrong). I think it's good enough. Thanks for the suggestion!

**Comment by pedroapfilho** [comment]
Created the PR for it! Check it out if you want to see the implementation!
