### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by gfsd3v** [pedroapfilho/2captcha-node#9]
Hi, as of today I'm having a little trouble using the library, every time I call the solve method I get the following error:

`Error: TypeError: Cannot read property 'name' of undefined\n    at /Users/gabriel/repos/invoice-parser/node_modules/2captcha-node/dist/index.js:78:27\n    at step (/Users/gabriel/repos/invoice-parser/node_modules/2captcha-node/dist/index.js:33:23)\n    at Object.next (/Users/gabriel/repos/invoice-parser/node_modules/2captcha-node/dist/index.js:14:53)\n    at /Users/gabriel/repos/invoice-parser/node_modules/2captcha-node/dist/index.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/gabriel/repos/invoice-parser/node_modules/2captcha-node/dist/index.js:4:12)\n    at postCaptcha (/Users/gabriel/repos/invoice-parser/node_modules/2captcha-node/dist/index.js:47:49)\n    at /Users/gabriel/repos/invoice-parser/node_modules/2captcha-node/dist/index.js:127:50\n    at step (/Users/gabriel/repos/invoice-parser/node_modules/2captcha-node/dist/index.js:33:23)\n    at Object.next (/Users/gabriel/repos/invoice-parser/node_modules/2captcha-node/dist/index.js:14:53)`

Any ideia of what could be or how to fix it ? Thanks for the awesome work!

**Comment by pedroapfilho** [comment]
Hey, sorry.

I made a breaking change and now it looks like this:

```js
const options = {
  image: "base64-image",
  maxAttempts: 60 // Optional
};

const solvedCaptcha = await captcha.solve(options);
```
